''''
Contains the Constants used by ansible modules
'''
NETORCA_STATES_REJECTED = 'REJECTED'
NETORCA_STATES_PENDING = 'PENDING'
NETORCA_STATES_APPROVED = 'APPROVED'
NETORCA_STATES_COMPLETED = 'COMPLETED'
NETORCA_VALID_STATES = [
    NETORCA_STATES_REJECTED,
    NETORCA_STATES_PENDING,
    NETORCA_STATES_APPROVED,
    NETORCA_STATES_COMPLETED
]

FIELDS_URL = 'url'
FIELDS_USER = 'username'
FIELDS_API_KEY = 'token'
FIELDS_PASS = 'password'
FIELDS_STATE = 'state'
FIELDS_SERVICE = 'service_name'
FIELDS_UUID = 'uuid'
FIELDS_DEPLOYED_ITEM = 'deployed_item'
